name: CI_UPDATED
on:
  pull_request_target:
    types: [labeled, opened, synchronize]
jobs:
  build:
    if: (github.event.action == 'labeled' && github.event.pull_request.base.head.repo.full_name != 'brunoeduardodev/gh-actions-pull-request-target-playground' && github.event.label.name == 'run-ci') || (github.event.action != 'labeled' && github.event.pull_request.base.head.repo.full_name == 'brunoeduardodev/gh-actions-pull-request-target-playground')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@v4
        with: 
          version: 8
          run_install: false
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: echo "Secret is ${{ secrets.secret }}"
      - run: SECRET=${{ secrets.secret }} pnpm run start
